"""Add column to Photo (who_liked and likes)

Revision ID: ebd7c6e9eb20
Revises: a32e0aff5fb1
Create Date: 2023-11-18 19:54:18.818973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd7c6e9eb20'
down_revision: Union[str, None] = 'a32e0aff5fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('who_liked', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'who_liked')
    op.drop_column('photos', 'likes')
    # ### end Alembic commands ###
